// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Kr1h_zuQe5W5sUYuxLH3hZtjQ67mDik',
    appId: '1:749204358724:web:e0f012fd8b6b086b861e11',
    messagingSenderId: '749204358724',
    projectId: 'devgram-24b98',
    authDomain: 'devgram-24b98.firebaseapp.com',
    storageBucket: 'devgram-24b98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWgogO4I1PUXTFdrvzDLkhE7vrmApqeQg',
    appId: '1:749204358724:android:8a16e1ac6ab30453861e11',
    messagingSenderId: '749204358724',
    projectId: 'devgram-24b98',
    storageBucket: 'devgram-24b98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbOn7lGnqpzgQ72pEgQ4SlpLOnlF1WGHs',
    appId: '1:749204358724:ios:a1526193e55c40ec861e11',
    messagingSenderId: '749204358724',
    projectId: 'devgram-24b98',
    storageBucket: 'devgram-24b98.firebasestorage.app',
    iosBundleId: 'com.example.devgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbOn7lGnqpzgQ72pEgQ4SlpLOnlF1WGHs',
    appId: '1:749204358724:ios:a1526193e55c40ec861e11',
    messagingSenderId: '749204358724',
    projectId: 'devgram-24b98',
    storageBucket: 'devgram-24b98.firebasestorage.app',
    iosBundleId: 'com.example.devgram',
  );
}
